# Generated by Django 5.0.6 on 2024-06-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Projects',
        ),
    ]
