# Generated by Django 5.0.6 on 2024-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_news_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
    ]
