# Generated by Django 5.0.6 on 2024-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_content_alter_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
