# Generated by Django 5.0.6 on 2024-06-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderitem_remove_product_orders_delete_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название услуги'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
